// Each new term in the Fibonacci sequence
// is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence
// whose values do not exceed four million, find the sum
// of the even-valued terms.

let rec fib n =
  match n with
  | 1 | 2 -> 1
  | n -> fib(n-1) + fib(n-2)


let rec evenFibSum n sum =
  let res = fib n
  if res % 2 = 0 then
    evenFibSum (n+1) (sum+res)
  elif res > 4000000 then
    sum
  else
    evenFibSum (n+1) sum


let res = evenFibSum 1 0
printfn "%d" res
